Error: object 'coinLIst' not found
 

[1] "Error in colnamesInt(x, names(on), check_dups = FALSE) : \n  argument specifying columns specify non existing column(s): cols[1]='currency'\n"

[1] "Error in `[.data.table`(momentumList, , `:=`(symbol, sapply(momentumList,  : \n  Supplied 6 items to be assigned to 5 items of column 'symbol'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.\n"

[1] "Error in colnamesInt(i, unname(on), check_dups = FALSE) : \n  argument specifying columns specify non existing column(s): cols[1]='symbol'\n"

